name: SimpleModerator
main: com.evosysdev.bukkit.taylorjb.simplemod.SimpleMod
version: 0.4.6
website: http://dev.bukkit.org/server-mods/simplemoderator/
author: taylorjb
permissions:
    simplemod:
        description: Gives access to SimpleModerator help command
    simplemod.*:
        description: Gives access to all SimpleMod commands
        children:
            simplemod: true
            simplemod.ban: true
            simplemod.unban: true
            simplemod.ipban: true
            simplemod.unbanip: true
            simplemod.mute: true
            simplemod.unmute: true
            simplemod.kick: true
    simplemod.ban:
        description: Allows you to ban a user
        children:
            simplemod.ban.temp: true
    simplemod.ban.temp:
        description: Allows you to temporarily ban a user
    simplemod.unban:
        description: Allows you to unban a user
    simplemod.ipban:
        description: Allows you to IP ban a user
    simplemod.unbanip:
        description: Allows you to unban an IP address
    simplemod.mute:
        children:
            simplemod.mute.temp: true
    simplemod.mute.temp:
        description: Allows you to temporarily mute a user
    simplemod.unmute:
        description: Allows you to unmute a user
    simplemod.kick:
        description: Allows you to kick a user
commands:
    simplemoderator:
        aliases:
            - sa
            - sm
            - simplemod
        description: Displays SimpleMod help
        usage: |
            /<command> | Displays SimpleMod help
    ban:
        aliases:
        description: Ban a player
        usage: |
            /<command> <name> [reason] | Bans player with the given name=
    tempban:
        aliases:
            - tban
        description: Ban a player for some number of hours
        usage: |
            /<command> <name> <hours> [reason] | Bans player for given # of hours
    unban:
        aliases:
            - uban
        description: Unban a player
        usage: |
            /<command> <name> | Unbans player with the given name if they are banned
    banip:
        aliases:
            - ipban
            - iban
        description: Bans supplied player's IP address
        usage: |
            /<command> <name> [reason] | Bans supplied player's IP address
    unbanip:
        aliases:
            - uipban
            - uiban
            - ubanip
        description: Bans supplied player's IP address
        usage: |
            /<command> <IP address> | Unbans specified IP address
    mute:
        aliases:
        description: Mute a player
        usage: |
            /<command> <name> [reason] | Mutes player with the given name
    tempmute:
        aliases:
            - tmute
        description: Mute a player for some number of hours
        usage: |
            /<command> <name> <hours> [reason] | Mutes player for given # of hours
    unmute:
        aliases:
            - umute
        description: Unmute a player
        usage: |
            /<command> <name> | Unmutes player with given name
    kick:
        description: Kick a player
        usage: |
            /<command> <name> [reason] | Kicks player with given name