name: SimpleModerator
main: com.evosysdev.bukkit.taylorjb.simplemod.SimpleMod
version: 0.3.1
website: http://dev.bukkit.org/server-mods/simplemoderator/
author: tj007razor
permissions:
    simplemod:
        description: Gives access to SimpleModerator help command
    simplemod.ban:
        description: Allows you to ban a user
    simplemod.ban.temp:
        description: Allows you to temporarily ban a user
    simplemod.ipban:
        description: Allows you to IP ban a user
    simplemod.unban:
        description: Allows you to unban a user
    simplemod.mute:
        description: Allows you to mute a user
    simplemod.mute.temp:
        description: Allows you to temporarily mute a user
    simplemod.unmute:
        description: Allows you to unmute a user
    simplemod.kick:
        description: Allows you to kick a user
commands:
    simplemoderator:
        aliases:
            - sa
            - sm
            - simplemod
        description: Displays SimpleMod help
        usage: |
            /<command> | Displays SimpleMod help
    ban:
        aliases:
        description: Ban a player
        usage: |
            /<command> <name> | Bans player with the given name
            /<command> <name> <hours> | Bans player for given # of hours
    banip:
        aliases:
            - ipban
            - iban
        description: Bans supplied player's IP address
        usage:
            /<command> <name> | Bans supplied player's IP address
    unban:
        aliases:
            - uban
        description: Unban a player
        usage: |
            /<command> <name> | Unbans player with the given name if they are banned
    mute:
        aliases:
        description: Mute a player
        usage: |
            /<command> <name> | Mutes player with the given name
            /<command> <name> <hours> | Mutes player for given # of hours
    unmute:
        aliases:
            - umute
        description: Unmute a player
        usage: |
            /<command> <name> | Unmutes player with given name
    kick:
        description: Kick a player
        usage: |
            /<command> <name> | Kicks player with given name